<template><div><h1 id="form" tabindex="-1"><a class="header-anchor" href="#form" aria-hidden="true">#</a> Form</h1>
<p>表单支持对数据的创建以及编辑</p>
<h2 id="创建表单" tabindex="-1"><a class="header-anchor" href="#创建表单" aria-hidden="true">#</a> 创建表单</h2>
<h3 id="继承方式" tabindex="-1"><a class="header-anchor" href="#继承方式" aria-hidden="true">#</a> 继承方式</h3>
<p>表单继承了 <code v-pre>FormWidget</code></p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">class</span> <span class="token class-name-definition class-name">FormBanEstablish</span> <span class="token keyword">extends</span> <span class="token class-name">FormWidget</span>
<span class="token punctuation">{</span>
    <span class="token comment">// 设置标题</span>
    <span class="token keyword">protected</span> <span class="token keyword type-declaration">string</span> <span class="token variable">$title</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'新增'</span><span class="token punctuation">;</span>

    <span class="token comment">// 获取路由参数或者 Query 参数用于初始化</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">__construct</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token keyword static-context">parent</span><span class="token operator">::</span><span class="token function">__construct</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">id</span> <span class="token operator">=</span> <span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">input</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">// 对数据的处理, 这里的执行在表单验证过之后触发</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">handle</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$scope</span>                 <span class="token operator">=</span> <span class="token function">input</span><span class="token punctuation">(</span><span class="token class-name static-context">Scope</span><span class="token operator">::</span><span class="token constant">QUERY_NAME</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$input</span>                 <span class="token operator">=</span> <span class="token function">input</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$input</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'account_type'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token variable">$scope</span><span class="token punctuation">;</span>

        <span class="token variable">$Ban</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Ban</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token variable">$Ban</span><span class="token operator">-></span><span class="token function">establish</span><span class="token punctuation">(</span><span class="token variable">$input</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token class-name static-context">Resp</span><span class="token operator">::</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token variable">$Ban</span><span class="token operator">-></span><span class="token function">getError</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>

        <span class="token keyword">return</span> <span class="token class-name static-context">Resp</span><span class="token operator">::</span><span class="token function">success</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'操作成功'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'motion|grid:reload'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">// 返回模型数据</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword return-type">array</span>
    <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">id</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token variable">$pam</span> <span class="token operator">=</span> <span class="token class-name static-context">PamBan</span><span class="token operator">::</span><span class="token function">findOrFail</span><span class="token punctuation">(</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">id</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token keyword">return</span> <span class="token class-name static-context">Arr</span><span class="token operator">::</span><span class="token function">pluck</span><span class="token punctuation">(</span><span class="token variable">$pam</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'type'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'value'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'note'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">// 定义表单</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">form</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">select</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'type'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'类型'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">PamBan</span><span class="token operator">::</span><span class="token function">kvType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">rules</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
            <span class="token class-name static-context">Rule</span><span class="token operator">::</span><span class="token function">required</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'value'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'限制值'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">rules</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
            <span class="token class-name static-context">Rule</span><span class="token operator">::</span><span class="token function">required</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">help</span><span class="token punctuation">(</span><span class="token string double-quoted-string">"如果是Ip支持如下几种格式 :  固定IP(192.168.1.1) ; IP段 : (192.168.1.1-192.168.1.21);  IP 掩码(192.168.1.1/24); IP 通配符(192.168.1.*)"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'note'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'备注'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="简易方式" tabindex="-1"><a class="header-anchor" href="#简易方式" aria-hidden="true">#</a> 简易方式</h3>
<p>简易方式是允许在控制器中编写定义, 从而简化编写 form 的方式</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$form</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FormWidget</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$form</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'姓名'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$form</span><span class="token operator">-></span><span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'多厘'</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$form</span><span class="token operator">-></span><span class="token function">on</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token class-name static-context">Resp</span><span class="token operator">::</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token function">var_export</span><span class="token punctuation">(</span><span class="token function">input</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token variable">$form</span><span class="token operator">-></span><span class="token function">resp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="分组方式" tabindex="-1"><a class="header-anchor" href="#分组方式" aria-hidden="true">#</a> 分组方式</h2>
<p>对于模型中有些数据可能需要多个数据来支持, 根据字段再去拆分结构, 使用 <code v-pre>.</code> 来进行拆分字段, 这里的渲染和标准的 html 有所不同</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">class</span> <span class="token class-name-definition class-name">FormFieldGroupEstablish</span> <span class="token keyword">extends</span> <span class="token class-name">FormWidget</span>
<span class="token punctuation">{</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">handle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token punctuation">}</span>

    <span class="token doc-comment comment">/**
     */</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword return-type">array</span>
    <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">[</span>
            <span class="token string single-quoted-string">'group'</span> <span class="token operator">=></span> <span class="token punctuation">[</span>
                <span class="token number">1</span>   <span class="token operator">=></span> <span class="token string single-quoted-string">'1-value'</span><span class="token punctuation">,</span>
                <span class="token string single-quoted-string">'a'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'a-value'</span><span class="token punctuation">,</span>
            <span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">form</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'group.1'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'1Value'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'group.a'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Group Val'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面对组件进行相应的介绍, 所有使用方式以以上两种方式为主</p>
<h2 id="组件" tabindex="-1"><a class="header-anchor" href="#组件" aria-hidden="true">#</a> 组件</h2>
<h3 id="table-表格" tabindex="-1"><a class="header-anchor" href="#table-表格" aria-hidden="true">#</a> Table - 表格</h3>
<p>表格组件, 支持行内编辑</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 这个表格支持编辑模式</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">FormTableEstablish</span> <span class="token keyword">extends</span> <span class="token class-name">FormWidget</span>
<span class="token punctuation">{</span>
    <span class="token comment">// 设置标题</span>
    <span class="token keyword">protected</span> <span class="token keyword type-declaration">string</span> <span class="token variable">$title</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'表格'</span><span class="token punctuation">;</span>

    <span class="token comment">// 返回模型数据</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword return-type">array</span>
    <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">[</span>
            <span class="token string single-quoted-string">'table'</span> <span class="token operator">=></span> <span class="token punctuation">[</span>
                <span class="token punctuation">[</span> <span class="token string single-quoted-string">'id'</span>   <span class="token operator">=></span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'多厘'</span><span class="token punctuation">,</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
                <span class="token punctuation">[</span> <span class="token string single-quoted-string">'id'</span>   <span class="token operator">=></span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'name'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'晴天'</span><span class="token punctuation">,</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token punctuation">]</span>
        <span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token comment">// 定义表单</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">form</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">table</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'table'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'表格'</span><span class="token punctuation">)</span>
            <span class="token comment">// 定义列</span>
            <span class="token operator">-></span><span class="token function">cols</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'name'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'用户名'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="eztable-表格预览" tabindex="-1"><a class="header-anchor" href="#eztable-表格预览" aria-hidden="true">#</a> EzTable - 表格预览</h3>
<p>表格预览组件仅仅用于渲染数据, 当前支持文字, 图片渲染</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>EzTable</span><span class="token punctuation">;</span>
<span class="token comment">// ...</span>
<span class="token variable">$this</span><span class="token operator">-></span><span class="token function">ezTable</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'ez-table'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'表格'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">easy</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string single-quoted-string">'Header'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Title'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Value'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'图片'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string single-quoted-string">'网站'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地址'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'https://www.baidu.com'</span><span class="token punctuation">,</span> <span class="token class-name static-context">EzTable</span><span class="token operator">::</span><span class="token function">image</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'https://start.wulicode.com/img/428x280/wulicode'</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token string single-quoted-string">'网站'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'名称'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'百度'</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// ...</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="cascader-级联选择" tabindex="-1"><a class="header-anchor" href="#cascader-级联选择" aria-hidden="true">#</a> Cascader - 级联选择</h3>
<p>级联选择可用于级联选择, 数据返回以数组为主</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">class</span> <span class="token class-name-definition class-name">FormFieldCascaderEstablish</span> <span class="token keyword">extends</span> <span class="token class-name">FormWidget</span>
<span class="token punctuation">{</span>
    <span class="token keyword">protected</span> <span class="token keyword type-declaration">string</span> <span class="token variable">$title</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'级联选择'</span><span class="token punctuation">;</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">handle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token punctuation">}</span>

    <span class="token doc-comment comment">/**
     */</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword return-type">array</span>
    <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">[</span>
            <span class="token string single-quoted-string">'province'</span>    <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'city'</span>        <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">35</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'area'</span>        <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">468</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'area-filter'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">36</span><span class="token punctuation">,</span> <span class="token number">468</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'area-sub'</span>    <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">36</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'area-lazy'</span>   <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">,</span> <span class="token number">36</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        <span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">form</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token comment">// 选择地区</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'province'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'city'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'城市'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'city'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 指定宽度</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">300</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 指定可筛选</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area-filter'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区(可筛选)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">filterable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 开启父选项可选择</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area-sub'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区(选择两级)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">300</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">checkStrictly</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 开启多选</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area-muti'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区(选择两级)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area'</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
            <span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">300</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">checkStrictly</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">multi</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 开启懒加载模式(当前模式下暂时无法恢复数据)</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'area-lazy'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'地区(懒加载)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">SysArea</span><span class="token operator">::</span><span class="token function">cascader</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'city'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">300</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">lazy</span><span class="token punctuation">(</span>
            <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.form.cascader'</span><span class="token punctuation">)</span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">disableReset</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


