<template><div><h1 id="table" tabindex="-1"><a class="header-anchor" href="#table" aria-hidden="true">#</a> Table</h1>
<p>列渲染, 列采用如下方式进行列的添加</p>
<h2 id="添加列" tabindex="-1"><a class="header-anchor" href="#添加列" aria-hidden="true">#</a> 添加列</h2>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">table</span><span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">quickId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="设置基础属性" tabindex="-1"><a class="header-anchor" href="#设置基础属性" aria-hidden="true">#</a> 设置基础属性</h2>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">table</span><span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span>
        <span class="token comment">// 定义最小宽度</span>
        <span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span>
        <span class="token comment">// 固定最小宽度</span>
        <span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span>
        <span class="token comment">// 设置展示位置, 默认 left, 可选 [left,center,right]</span>
        <span class="token operator">-></span><span class="token function">align</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'left'</span><span class="token punctuation">)</span>
        <span class="token comment">// 标识列为可排序</span>
        <span class="token operator">-></span><span class="token function">sortable</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token comment">// 标识列为可fix 显示, 默认是右侧, 可以设置为 [left, right], 例如操作按钮可固定在右侧展示</span>
        <span class="token operator">-></span><span class="token function">fixed</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'right'</span><span class="token punctuation">)</span>
        <span class="token comment">// 文字显示为一行, 并且多余使用省略号</span>
        <span class="token operator">-></span><span class="token function">ellipsis</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token comment">// 纯文本可复制</span>
        <span class="token operator">-></span><span class="token function">copyable</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="快捷样式" tabindex="-1"><a class="header-anchor" href="#快捷样式" aria-hidden="true">#</a> 快捷样式</h2>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">table</span><span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span>
        <span class="token comment">// 渲染为ID, 固定宽度, 并将ID 居中, 普通模式 5位数值, large模式 7 位数字</span>
        <span class="token operator">-></span><span class="token function">quickId</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token operator">-></span><span class="token function">quickId</span><span class="token punctuation">(</span><span class="token constant boolean">true</span><span class="token punctuation">)</span>

        <span class="token comment">// 渲染为标题, 默认显示 15个汉字, large 模式显示 20个汉字左右</span>
        <span class="token operator">-></span><span class="token function">quickTitle</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token operator">-></span><span class="token function">quickTitle</span><span class="token punctuation">(</span><span class="token constant boolean">true</span><span class="token punctuation">)</span>

        <span class="token comment">// 渲染为 Y-m-d h:i:s 宽度并居中</span>
        <span class="token operator">-></span><span class="token function">quickDatetime</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

        <span class="token comment">// 定义 Icon 的快捷数量, 宽度根据数量来进行计算</span>
        <span class="token operator">-></span><span class="token function">quickIcon</span><span class="token punctuation">(</span><span class="token variable">$num</span> <span class="token operator">=</span> <span class="token number">3</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="自定义展示" tabindex="-1"><a class="header-anchor" href="#自定义展示" aria-hidden="true">#</a> 自定义展示</h2>
<p>列渲染展示, 添加列若是模型存在的数据, 则原样展示, 如果没有, 或者需要对数据进行组合, 格式化, 可以采用自定义的渲染方式</p>
<p>如果存在 ID, 则展示为 ID</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>如果想把用户的手机号进行隐藏展示, 并且手机号是存在的字段</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'mobile'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'用户手机号'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">display</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$value</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token function">substr</span><span class="token punctuation">(</span><span class="token variable">$value</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token operator">.</span><span class="token string single-quoted-string">'****'</span><span class="token operator">.</span><span class="token function">substr</span><span class="token punctuation">(</span><span class="token variable">$value</span><span class="token punctuation">,</span> <span class="token number">8</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果想组合两个字段的展示, 例如用户的姓名和部门是两个字段</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 这里 $this 返回的是模型的一行数据</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'info'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'姓名(部门)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">display</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token variable">$value</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">truename</span><span class="token operator">.</span><span class="token string double-quoted-string">"(<span class="token interpolation"><span class="token punctuation">{</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">department</span><span class="token punctuation">}</span></span>)"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="快捷渲染" tabindex="-1"><a class="header-anchor" href="#快捷渲染" aria-hidden="true">#</a> 快捷渲染</h2>
<p>这里也定义快捷的渲染方法, 渲染方法使用 <code v-pre>asXx</code> 格式</p>
<h3 id="link" tabindex="-1"><a class="header-anchor" href="#link" aria-hidden="true">#</a> link</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 渲染为可点击的链接地址</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'url'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'用户主页'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token operator">-></span><span class="token function">asLink</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="html" tabindex="-1"><a class="header-anchor" href="#html" aria-hidden="true">#</a> Html</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 渲染为Html</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'color'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Html'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asHtml</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token string double-quoted-string">"&lt;div style='<span class="token interpolation"><span class="token punctuation">{</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">style</span><span class="token punctuation">}</span></span>'><span class="token interpolation"><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">title</span></span>&lt;/div>"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="image" tabindex="-1"><a class="header-anchor" href="#image" aria-hidden="true">#</a> Image</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 图片, 将存储的图片地址以图片的形式展示到数据行中</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'image'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'图片'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asImage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="download" tabindex="-1"><a class="header-anchor" href="#download" aria-hidden="true">#</a> Download</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 可下载, 渲染为下载按钮</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'pdf'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Pdf'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asDownload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="onoff" tabindex="-1"><a class="header-anchor" href="#onoff" aria-hidden="true">#</a> OnOff</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 显示为快捷开关</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Loading'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asOnOff</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="kv" tabindex="-1"><a class="header-anchor" href="#kv" aria-hidden="true">#</a> Kv</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 使用定义的状态字段来返回</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'status'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'usingKv'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asKv</span><span class="token punctuation">(</span><span class="token class-name static-context">DemoWebapp</span><span class="token operator">::</span><span class="token function">kvStatus</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="date" tabindex="-1"><a class="header-anchor" href="#date" aria-hidden="true">#</a> Date</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 显示为可以格式化的时间</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'date'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'创建时间'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asDate</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'m-d h:i'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 根据语言显示为 距今 xxx 形式</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'date'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'创建时间'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asDiffForHumans</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="util" tabindex="-1"><a class="header-anchor" href="#util" aria-hidden="true">#</a> Util</h3>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 根据语言显示为 距今 xxx 形式</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'filesize'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'文件体积'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asFilesize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 显示为隐藏数据, 并可以自定义接口来返回数据并显示在列表中</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'filesize'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'文件体积'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asHidden</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="列编辑" tabindex="-1"><a class="header-anchor" href="#列编辑" aria-hidden="true">#</a> 列编辑</h2>
<p>支持行内编辑, 文本模式, 开关模式, 选择模式, 如果不指定地址, 则采用模型的数据进行修改, 此功能对于不敏感的数据进行编辑, 如果涉及到业务逻辑的数据, 建议使用自定义地址进行修改</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token comment">// 支持编辑, 并支持字段更换名称</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading-alt'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(字段更名)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsOnOff</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">loading</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">query</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 禁用指定行的数据进行编辑</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading-disable'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(禁用部分)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsOnOff</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">loading</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">id</span> <span class="token operator">%</span> <span class="token number">3</span> <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">query</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// 自定义Url进行编辑</span>
<span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading-url'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(自定义Url)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsOnOff</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">loading</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">query</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.mgr_app.grid_modify_loading'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当前支持的几个类型为</p>
<h3 id="select" tabindex="-1"><a class="header-anchor" href="#select" aria-hidden="true">#</a> Select</h3>
<p>选择数据进行提交</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'status-alt'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(字段更名)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsSelect</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">status</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">query</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'status'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">options</span><span class="token punctuation">(</span><span class="token class-name static-context">DemoWebapp</span><span class="token operator">::</span><span class="token function">kvStatus</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="onoff-1" tabindex="-1"><a class="header-anchor" href="#onoff-1" aria-hidden="true">#</a> OnOff</h3>
<p>开关</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'loading'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(字段更名)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsOnOff</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">loading</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="text" tabindex="-1"><a class="header-anchor" href="#text" aria-hidden="true">#</a> Text</h3>
<p>文字变更</p>
<div class="language-php line-numbers-mode" data-ext="php"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'sort-alt'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'行内编辑(字段更名)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">copyable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">editAsText</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">sort</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">query</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'sort'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


