<template><div><h1 id="grid" tabindex="-1"><a class="header-anchor" href="#grid" aria-hidden="true">#</a> Grid</h1>
<p>Grid 是项目的数据展示工具, 各个部件如下所示</p>
<p><img src="https://file.wulicode.com/note/2022/06-11/10-51-50606.png" alt=""></p>
<h2 id="编写" tabindex="-1"><a class="header-anchor" href="#编写" aria-hidden="true">#</a> 编写</h2>
<p>编写方式支持两种, 一种是单文件的方式, 就是将文件的内容按照约定填写到指定的列表中, 使用起来更加独立, 另外一种就是小的列表写入到单个控制器中使用起来更加灵活</p>
<h3 id="单文件方式" tabindex="-1"><a class="header-anchor" href="#单文件方式" aria-hidden="true">#</a> 单文件方式</h3>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Filter<span class="token punctuation">\</span>FilterPlugin</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Grid<span class="token punctuation">\</span>GridBase</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Grid<span class="token punctuation">\</span>Tools<span class="token punctuation">\</span>Interactions</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>Render<span class="token punctuation">\</span>GridActions</span><span class="token punctuation">;</span>
<span class="token keyword">use</span> <span class="token package">Poppy<span class="token punctuation">\</span>MgrApp<span class="token punctuation">\</span>Classes<span class="token punctuation">\</span>Table<span class="token punctuation">\</span>TablePlugin</span><span class="token punctuation">;</span>

<span class="token keyword">class</span> <span class="token class-name-definition class-name">GridLayout</span> <span class="token keyword">extends</span> <span class="token class-name">GridBase</span>
<span class="token punctuation">{</span>
    <span class="token keyword">public</span> <span class="token keyword type-declaration">string</span> <span class="token variable">$title</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'布局'</span><span class="token punctuation">;</span>

    <span class="token doc-comment comment">/**
     * <span class="token keyword">@inheritDoc</span>
     */</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">table</span><span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token comment">// 自定义样式</span>
        <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">quickId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">sortable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'title'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'标题'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'user.nickname'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'Nickname(联合查询)'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">quickTitle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'created_at'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">quickDatetime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'handle'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'操作'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asAction</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">GridActions</span> <span class="token variable">$actions</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">quickIcon</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$row</span> <span class="token operator">=</span> <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">getRow</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'错误'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.grid.request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'error'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Close'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">danger</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'成功'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.grid.request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'success'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Check'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">success</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'确认'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.grid.request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'success'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">confirm</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'QuestionFilled'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">warning</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Disabled'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.grid.request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'success'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">disabled</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Minus'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">page</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'页面'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.form.auto'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'field-color'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'form'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Edit'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">info</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">copy</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'复制'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'复制自定义的内容'</span> <span class="token operator">.</span> <span class="token variable">$row</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">quickIcon</span><span class="token punctuation">(</span><span class="token number">6</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>


    <span class="token doc-comment comment">/**
     * <span class="token keyword">@inheritDoc</span>
     */</span>
    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">filter</span><span class="token punctuation">(</span><span class="token class-name type-declaration">FilterPlugin</span> <span class="token variable">$filter</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$filter</span><span class="token operator">-></span><span class="token function">action</span><span class="token punctuation">(</span><span class="token number">6</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token variable">$filter</span><span class="token operator">-></span><span class="token function">like</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'title'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'标题'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token number">4</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">quick</span><span class="token punctuation">(</span><span class="token class-name type-declaration">Interactions</span> <span class="token variable">$actions</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">page</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'快捷操作'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.form.auto'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'field-color'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'form'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">icon</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Plus'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">batch</span><span class="token punctuation">(</span><span class="token class-name type-declaration">Interactions</span> <span class="token variable">$actions</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
        <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'批量操作'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.grid.request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'success'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="控制器方式" tabindex="-1"><a class="header-anchor" href="#控制器方式" aria-hidden="true">#</a> 控制器方式</h3>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token comment">// 第一列显示id字段，并将这一列设置为可排序列</span>
<span class="token variable">$grid</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">GridWidget</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">QueryDemoWebapp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$grid</span><span class="token operator">-></span><span class="token function">table</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">TablePlugin</span> <span class="token variable">$table</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'ID'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'title'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'标题'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$grid</span><span class="token operator">-></span><span class="token function">batch</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">Interactions</span> <span class="token variable">$actions</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'批量删除'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">''</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$grid</span><span class="token operator">-></span><span class="token function">quick</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">Interactions</span> <span class="token variable">$actions</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">page</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'添加'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">''</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'form'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token variable">$grid</span><span class="token operator">-></span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">FilterPlugin</span> <span class="token variable">$filter</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token variable">$filter</span><span class="token operator">-></span><span class="token function">gt</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'status'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'状态'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asText</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">return</span> <span class="token variable">$grid</span><span class="token operator">-></span><span class="token function">resp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="filter" tabindex="-1"><a class="header-anchor" href="#filter" aria-hidden="true">#</a> Filter</h2>
<blockquote>
<p>表的搜索工具</p>
</blockquote>
<h2 id="batch" tabindex="-1"><a class="header-anchor" href="#batch" aria-hidden="true">#</a> Batch</h2>
<blockquote>
<p>对数据的批处理</p>
</blockquote>
<h2 id="render" tabindex="-1"><a class="header-anchor" href="#render" aria-hidden="true">#</a> Render</h2>
<p>列显示的渲染</p>
<h2 id="action" tabindex="-1"><a class="header-anchor" href="#action" aria-hidden="true">#</a> Action</h2>
<p>操作 <a href="#action">Action</a> 是触发全局动作, 参考 Action 部分</p>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token variable">$table</span><span class="token operator">-></span><span class="token function">add</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'handle'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'操作'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">asAction</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token class-name type-declaration">ActionsRender</span> <span class="token variable">$actions</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">request</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'成功'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.mgr_app.grid_request'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'success'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">page</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'页面'</span><span class="token punctuation">,</span> <span class="token function">route</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'demo:api.mgr_app.grid_form'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string single-quoted-string">'detail'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'form'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token variable">$actions</span><span class="token operator">-></span><span class="token function">target</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Target(百度)'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'https://www.baidu.com'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="模型-model" tabindex="-1"><a class="header-anchor" href="#模型-model" aria-hidden="true">#</a> 模型 Model</h2>
<p><img src="https://file.wulicode.com/note/2022/06-25/16-26-37428.png" alt=""></p>
<p>有些情况下单模型或者简单模型的查询不会满足要求或者数据量过大导致性能异常, 这里扩展出来一个类 <code v-pre>QueryCustom</code> 进行自定义查询</p>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token keyword">class</span> <span class="token class-name-definition class-name">QueryDemoWebapp</span> <span class="token keyword">extends</span> <span class="token class-name">QueryCustom</span>
<span class="token punctuation">{</span>

    <span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token class-name return-type">Collection</span>
    <span class="token punctuation">{</span>
        <span class="token comment">// 参数</span>
        <span class="token variable">$params</span> <span class="token operator">=</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">params</span><span class="token punctuation">;</span>
        <span class="token variable">$Object</span> <span class="token operator">=</span> <span class="token class-name static-context">DemoWebapp</span><span class="token operator">::</span><span class="token function">whereRaw</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id % 3 =0'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 总数</span>
        <span class="token variable">$this</span><span class="token operator">-></span><span class="token property">total</span> <span class="token operator">=</span> <span class="token variable">$Object</span><span class="token operator">-></span><span class="token function">count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 返回自定义的数据</span>
        <span class="token keyword">return</span> <span class="token variable">$Object</span><span class="token operator">-></span><span class="token function">take</span><span class="token punctuation">(</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">pagesize</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">offset</span><span class="token punctuation">(</span><span class="token variable">$this</span><span class="token operator">-></span><span class="token property">pageOffset</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以下模型的几个方法说明如下</p>
<h3 id="get" tabindex="-1"><a class="header-anchor" href="#get" aria-hidden="true">#</a> get</h3>
<p>获取的数据即可</p>
<h3 id="edit" tabindex="-1"><a class="header-anchor" href="#edit" aria-hidden="true">#</a> edit</h3>
<p>用于行内编辑</p>
<h3 id="getprimarykey" tabindex="-1"><a class="header-anchor" href="#getprimarykey" aria-hidden="true">#</a> getPrimaryKey</h3>
<p>获取组件</p>
<h3 id="chunk" tabindex="-1"><a class="header-anchor" href="#chunk" aria-hidden="true">#</a> chunk</h3>
<p>用于导出数据时候批量读取数据</p>
<h3 id="prepare" tabindex="-1"><a class="header-anchor" href="#prepare" aria-hidden="true">#</a> prepare</h3>
<p>用于在读取数据的时候引用查询对象和查询列数据</p>
</div></template>


